# generated by datamodel-codegen:
#   filename:  case_settings.yml
#   timestamp: 2025-03-14T17:39:51+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class Sampler(BaseModel):
    type: str
    sample_count: int


class Integrator(BaseModel):
    type: str
    max_depth: int


class OutputItem(BaseModel):
    format: str
    file_name: str
    reference_wavelengths: Optional[List[int]] = None


class CaseConfig(BaseModel):
    file_type: str
    mitsuba_variant: str
    sampler: Sampler
    integrator: Integrator
    output: List[OutputItem]
