# generated by datamodel-codegen:
#   filename:  case_settings.yml
#   timestamp: 2025-03-14T17:39:51+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic.dataclasses import dataclass

from hysim.configs.constants import ConfigType, OutputFormat


@dataclass(frozen=True)
class Sampler:
    type: str
    sample_count: int

@dataclass(frozen=True)
class Integrator:
    type: str
    max_depth: int

@dataclass(frozen=True)
class OutputItem:
    format: OutputFormat
    file_name: str
    reference_wavelengths: Optional[List[int]] = None

@dataclass(frozen=True)
class CaseConfig:
    file_type: ConfigType
    mitsuba_variant: str
    sampler: Sampler
    integrator: Integrator
    output: List[OutputItem]
