# generated by datamodel-codegen:
#   filename:  materials.yml
#   timestamp: 2025-03-22T11:47:32+00:00

from __future__ import annotations

from typing import Dict

from pydantic.dataclasses import dataclass

from hysim.configs.constants import ConfigType
from hysim.mitsuba.bsdfs import BSDFs

@dataclass
class MaterialWrapper:
    material: BSDFs


class MaterialsConfig:
    file_type: ConfigType.MISSION
    materials : Dict[str, BSDFs]

    def __init__(self, file_type: str):
        self.file_type = file_type
        self.materials = {}
