# generated by datamodel-codegen:
#   filename:  mission_parameters.yml
#   timestamp: 2025-03-14T17:39:32+00:00

from __future__ import annotations

from typing import List, Union, Literal

from pydantic.dataclasses import dataclass

from hysim.configs.constants import ConfigType


@dataclass(frozen=True)
class Spacecraft:
    position_frame: str
    position: List[str]
    attitude: List[float]

# class TargetSpacecraft(Spacecraft):
#     pass

@dataclass(frozen=True)
class ChaserSpacecraft(Spacecraft):
    attitude: Union[List[float], Literal["lookat"]]
    @property
    def is_lookat(self) -> bool:
        return self.attitude == "lookat"


@dataclass(frozen=True)
class MissionConfig:
    file_type: ConfigType
    datetime: str
    target: Spacecraft
    chaser: ChaserSpacecraft
