# generated by datamodel-codegen:
#   filename:  mission_parameters.yml
#   timestamp: 2025-03-14T17:39:32+00:00

from __future__ import annotations

from typing import List, Union

from pydantic import BaseModel

class Spacecraft(BaseModel):
    position_frame: str
    position: List[str]
    attitude: Union[List[float], str]

# class TargetSpacecraft(Spacecraft):
#     pass
# class ChaserSpacecraft(Spacecraft):
#     pass

class MissionConfig(BaseModel):
    file_type: str
    datetime: str
    target: Spacecraft
    chaser: Spacecraft
