[build-system]
requires = [
    "setuptools",
    "setuptools-scm",
    "wheel"]
build-backend = "setuptools.build_meta"


[project]
# Project Information
name = "hysim" # Required
version = "0.4.0"
description = "Hyperspectral Space-to-Space Imaging Simulator"
requires-python = ">=3.9"
authors = [
    {name = "Cameron Leslie", email= "cameron.f.leslie@cranfield.ac.uk"},
    {name = "Leonard Felicetti", email= "Leonard.Felicetti@cranfield.ac.uk"},
    {name = "Stephen Hobbs", email= "S.E.Hobbs@cranfield.ac.uk"},
    {name = "Samuel Rowling"},
]
maintainers = [
     {name = "Cameron Leslie", email= "cameron.f.leslie@cranfield.ac.uk"}
]
readme = "README.md"

classifiers=[
     "Development Status :: Pre-Alpha",
]

dependencies = [
    "numpy==2.0.2",
    "mitsuba==3.7.1",
    "rickle==1.2.3",
    "spiceypy==6.0.0",
    "pydantic==2.11.7",
    "Pillow==12.0.0",
    "pydantic==2.12.3",
    "rich==14.2.0",
]

[tool.mypy]
plugins = ['pydantic.mypy', "numpy.typing.mypy_plugin"]

[project.scripts]
hysim = "hysim.cli:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.distutils.bdist_wheel]
universal = true
