---
# ========================================================================
# Case Settings Configuration File
# ========================================================================
# File type: specifies the type of configuration file to be interpreted by
# the program.
file_type: case_config

# ------------------------------------------------------------------------
# Render Settings
integrator:
  type: stratified
  sample_count: 128 # Multiples of 8

sampler:
  type: path
  max_depth: -1 # -1 for infinite

# ------------------------------------------------------------------------
# Output Settings
output:
  - format: exr
    file_name: hdr_case_results.exr
  - format: binary
    file_name: binary_case_results

# ------------------------------------------------------------------------
# Log Settings
log: 
  save_case_log: True
  file_name: case_log